FROM node:10.12-alpine as node

RUN apk update && apk add git

WORKDIR /application

COPY package.json yarn.lock ./

RUN yarn install --production

COPY . /application

RUN npm rebuild node-sass && yarn build

FROM nginx:1.15.4

WORKDIR /var/www/static
COPY --from=node /application/dist/ /var/www/static

COPY ./etc/nginx/prod.conf /etc/nginx/conf.d/default.conf
