FROM node:10.12-alpine as node

RUN apk update && apk add git

WORKDIR /application

COPY package.json package-lock.json ./

RUN npm install

COPY . /application

RUN npm rebuild node-sass && npm run build && npm prune --production

FROM nginx:1.15.4

WORKDIR /var/www/static
COPY --from=node /application/dist/ /var/www/static
