export default function getCountriesByRegion(region) {
  const regions = {
    north_america: [
      'Antigua and Barbuda',
      'Barbados',
      'Belize',
      'Bermuda',
      'Canada',
      'Commonwealth of Dominica',
      'Commonwealth of the Bahamas',
      'Dominican Republic',
      'Grenada',
      'Jamaica',
      'Republic of Costa Rica',
      'Republic of Cuba',
      'Republic of El Salvador',
      'Republic of Guatemala',
      'Republic of Haiti',
      'Republic of Honduras',
      'Republic of Nicaragua',
      'Republic of Panama',
      'Republic of Trinidad and Tobago',
      'Saint Kitts and Nevis',
      'Saint Lucia',
      'Saint Vincent and The Grenadines',
      'United Mexican States',
      'United States of America',
    ],
    eu: [
      'Austria',
      'Belgium',
      'Bulgaria',
      'Croatia',
      'Czech Republic',
      'Denmark',
      'Estonia',
      'Finland',
      'France',
      'Germany',
      'Greece',
      'Hungary',
      'Ireland',
      'Italy',
      'Latvia',
      'Lithuania',
      'Luxembourg',
      'Malta',
      'Netherlands',
      'Poland',
      'Portugal',
      'Republic of Cyprus',
      'Romania',
      'Slovakia',
      'Slovenia',
      'Spain',
      'Sweden',
    ],
    uk: ['England', 'Scotland', 'Wales', 'Northern Ireland'],
    russia: ['Russia'],
    worldwide: [
      'Afghanistan',
      'Australia',
      'Azerbaijan',
      'Bangladesh',
      'Brazil',
      'China',
      'Egypt',
      'Ethiopia',
      'India',
      'Indonesia',
      'Japan',
      'Nigeria',
      'Pakistan',
      'Philippines',
      'Vietnam',
      'etc.',
    ],
  };

  return regions[region];
}
