export default function getCountriesByRegion(region) {
  const regions = {
    europe: [
      'Åland Islands',
      'Albania',
      'Andorra',
      'Austria',
      'Belgium',
      'Bosnia and Herzegovina',
      'Bulgaria',
      'Croatia',
      'Cyprus',
      'Czech',
      'Denmark',
      'Estonia',
      'Faroe Islands',
      'Finland',
      'France',
      'Germany',
      'Gibraltar',
      'Greece',
      'Guernsey',
      'Hungary',
      'Iceland',
      'Ireland',
      'Isle Of Man',
      'Italy',
      'Jersey',
      'Latvia',
      'Liechtenstein',
      'Lithuania',
      'Luxembourg',
      'Malta',
      'Monaco',
      'Montenegro',
      'Netherlands',
      'North Macedonia',
      'Norway',
      'Poland',
      'Portugal',
      'Romania',
      'San Marino',
      'Serbia',
      'Slovakia',
      'Slovenia',
      'Spain',
      'Svalbard and Jan Mayen',
      'Sweden',
      'Switzerland',
      'United Kingdom',
      'Vatican',
    ],
    russia_and_cis: [
      'Armenia',
      'Azerbaijan',
      'Belarus',
      'Georgia',
      'Kazakhstan',
      'Kyrgyzstan',
      'Moldova',
      'Russia',
      'Tajikistan',
      'Turkmenistan',
      'Ukraine',
      'Uzbekistan',
    ],
    asia: [
      'Afghanistan',
      'Bahrain',
      'Bangladesh',
      'British Indian Ocean Territory',
      'Brunei',
      'Butane',
      'Cambodia',
      'China (People`s Republic of China)',
      'Christmas Island',
      'Coconut islands',
      'DPRK (Democratic People`s Republic of Korea)',
      'East Timor',
      'Hong Kong',
      'India',
      'Indonesia',
      'Iran',
      'Iraq',
      'Israel',
      'Japan',
      'Jordan',
      'Kuwait',
      'Laos',
      'Lebanon',
      'Macau',
      'Malaysia',
      'Maldives',
      'Mongolia',
      'Myanmar',
      'Nepal',
      'Oman',
      'Pakistan',
      'Philippines',
      'Qatar',
      'Saudi Arabia',
      'Singapore',
      'Sri Lanka',
      'State of Palestine',
      'Syria',
      'Taiwan Province of China',
      'Thailand',
      'The Republic of Korea',
      'Turkey',
      'UAE',
      'Vietnam',
      'Yemen',
    ],
    latin_america: [
      'Argentina',
      'Belize',
      'Bolivia',
      'Bouvet Island',
      'Brazil',
      'Chile',
      'Colombia',
      'Costa Rica',
      'Ecuador',
      'Falkland Islands',
      'Guatemala',
      'Guiana',
      'Guyana',
      'Honduras',
      'Mexico',
      'Nicaragua',
      'Panama',
      'Paraguay',
      'Peru',
      'Salvador',
      'South Georgia and the South Sandwich Islands',
      'Suriname',
      'Uruguay',
      'Venezuela',
    ],
    worldwide: [
      'Algeria',
      'American Samoa',
      'Angola',
      'Anguilla',
      'Antarctica',
      'Antigua and Barbuda',
      'Aruba',
      'Australia',
      'Bahamas',
      'Barbados',
      'Benin',
      'Bermuda',
      'Bonaire, Sint Eustatius and Saba',
      'Botswana',
      'Burkina Faso',
      'Burundi',
      'Cameroon',
      'Canada',
      'Cape Verde',
      'CAR',
      'Cayman islands',
      'Chad',
      'Comoros',
      'Cook Islands',
      'Cote d’Ivoire',
      'Cuba',
      'Curacao',
      'Djibouti',
      'Dominica',
      'Dominican Republic',
      'DR Congo',
      'Egypt',
      'Equatorial Guinea',
      'Eritrea',
      'Esvatini',
      'Ethiopia',
      'Fiji',
      'French polynesia',
      'French Southern and Antarctic Territories',
      'Gabon',
      'Gambia',
      'Ghana',
      'Greenland',
      'Grenada',
      'Guadeloupe',
      'Guam',
      'Guinea',
      'Guinea bissau',
      'Haiti',
      'Hurd and MacDonald',
      'Islands of St. Helena, Ascension and Tristan da Cunha',
      'Jamaica',
      'Kenya',
      'Kiribati',
      'Lesotho',
      'Liberia',
      'Libya',
      'Madagascar',
      'Malawi',
      'Mali',
      'Marshall Islands',
      'Martinique',
      'Mauritania',
      'Mauritius',
      'Mayotte',
      'Micronesia',
      'Montserrat',
      'Morocco',
      'Mozambique',
      'Namibia',
      'Nauru',
      'New caledonia',
      'New Zealand',
      'Niger',
      'Nigeria',
      'Niue',
      'Norfolk Island',
      'Northern Mariana Islands',
      'Outer Small Islands (USA)',
      'Palau',
      'Papua New Guinea',
      'Pitcairn Islands',
      'Puerto rico',
      'Republic of the Congo',
      'Reunion',
      'Rwanda',
      'SADR',
      'Saint Barthelemy',
      'Saint Kitts and Nevis',
      'Saint lucia',
      'Saint martin',
      'Saint Pierre and Miquelon',
      'Saint Vincent and the Grenadines',
      'Samoa',
      'Sao Tome and Principe',
      'Senegal',
      'Seychelles',
      'Sierra leone',
      'Sint martin',
      'Solomon islands',
      'Somalia',
      'South Africa',
      'South sudan',
      'Sudan',
      'Tanzania',
      'Togo',
      'Tokelau',
      'Tonga',
      'Trinidad and Tobago',
      'Tunisia',
      'Turks and Caicos Islands',
      'Tuvalu',
      'Uganda',
      'USA',
      'Vanuatu',
      'Virgin Islands (UK)',
      'Virgin Islands (USA)',
      'Wallis and Futuna',
      'Zambia',
      'Zimbabwe',
    ],
  };

  return regions[region];
}
