export default function getCountriesByRegion(region) {
  const regions = {
    europe: [
      'Austria',
      'Belgium',
      'Bulgaria',
      'Croatia',
      'Czech Republic',
      'Denmark',
      'Estonia',
      'Finland',
      'France',
      'Germany',
      'Greece',
      'Hungary',
      'Ireland',
      'Italy',
      'Latvia',
      'Lithuania',
      'Luxembourg',
      'Malta',
      'Netherlands',
      'Poland',
      'Portugal',
      'Republic of Cyprus',
      'Romania',
      'Slovakia',
      'Slovenia',
      'Spain',
      'Sweden',
    ],
    russia_and_cis: [
      'Armenia',
      'Azerbaijan',
      'Belarus',
      'Kazakhstan',
      'Kyrgyzstan',
      'Moldova',
      'Russia',
      'Tajikistan',
      'Uzbekistan',
    ],
    asia: [
      'Afghanistan',
      'Bahrain',
      'Bangladesh',
      'Bhutan',
      'Brunei',
      'Myanmar',
      'Cambodia',
      'China',
      'Georgia',
      'Hong Kong',
      'India',
      'Indonesia',
      'Iran',
      'Iraq',
      'Israel',
      'Japan',
      'Jordan',
      'Kazakhstan',
      'North Korea',
      'South Korea',
      'Kuwait',
      'Kyrgyzstan',
      'Laos',
      'Lebanon',
      'Malaysia',
      'Maldives',
      'Mongolia',
      'Nepal',
      'Oman',
      'Pakistan',
      'Philippines',
      'Qatar',
      'Saudi Arabia',
      'Singapore',
      'Sri Lanka',
      'Syria',
      'Taiwan',
      'Tajikistan',
      'Thailand',
      'Timor-Leste',
      'Turkmenistan',
      'United Arab Emirates',
      'Uzbekistan',
      'Vietnam',
      'Yemen',
    ],
    latin_america: [
      'Argentina',
      'Bolivia',
      'Brazil',
      'Chile',
      'Colombia',
      'Dominican Republic',
      'Ecuador',
      'Republic of Costa Rica',
      'Republic of Cuba',
      'Republic of El Salvador',
      'Republic of Guatemala',
      'Republic of Honduras',
      'Republic of Nicaragua',
      'Republic of Panama',
      'Paraguay',
      'Peru',
      'Puerto Rico',
      'Uruguay',
      'Venezuela',
    ],
    worldwide: [
      'Australia',
      'Egypt',
      'Ethiopia',
      'Nigeria',
      'United Kingdom of Great Britain',
      'United States of America',
      'etc.',
    ],
  };

  return regions[region];
}
